"""Recover IMU noise parameters from the synthetic record and write sensor_params.json.

This is the hinge of the fidelity loop:

    generate_imu_data.py  ->  imu_raw.npz (+ ground-truth labels)
    fit_noise_params.py   ->  characterize -> recovered params -> configs/sensor_params.json
    (C++ Imu consumes the config; loop_closure.py re-derives the same params from sim output)

It (1) loads ``imu_raw.npz``, (2) runs the shared multi-axis Allan characterization,
(3) prints a recovered-vs-true comparison (should match within ~10-15% for the dominant
parameters), and (4) writes ``configs/sensor_params.json`` in the documented schema. The
``*_bias_instability`` field stores the recovered Gauss-Markov steady-state std
(``sigma_GM``) the C++ model expects — not the Allan hump-peak B (which is what we print
as the headline characterization number); the two differ by the fixed ~0.617 GM factor.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from characterize import characterize_axes

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_PATH = REPO_ROOT / "sensors" / "imu_raw.npz"
CONFIG_PATH = REPO_ROOT / "configs" / "sensor_params.json"

# Injected scale-factor errors (deterministic, not Allan-recoverable from a static record;
# scale factor only manifests on a non-zero true signal). Echoed through to the config so
# the in-sim sensor reproduces them. These mirror generate_imu_data.TRUE_*.scale_factor.
ACCEL_SCALE_FACTOR = 1.0e-3
GYRO_SCALE_FACTOR = 5.0e-4

# Seeker block kept sensible (LOS white/bias [rad], range-dependent glint). Not derived
# from the IMU record; characterized separately in a real program. Left as documented
# tactical defaults so the homing scenarios have a working seeker.
SEEKER_BLOCK = {
    "los_white": 3.0e-3,
    "los_bias": 5.0e-4,
    "glint": 2.0,
}


def _fmt_row(name: str, true: float, rec: float) -> str:
    err = 100.0 * (rec / true - 1.0) if true else float("nan")
    return f"  {name:16s} true {true:11.3e}   rec {rec:11.3e}   err {err:+6.1f}%"


def recover_and_write() -> dict:
    """Characterize both channels, print the comparison, and write sensor_params.json."""
    raw = np.load(RAW_PATH)
    dt = float(raw["dt"])

    results = {}
    print("Recovered-vs-true IMU noise parameters (Allan-variance characterization):\n")
    for ch in ("accel", "gyro"):
        _taus, _adev, _edf, fit = characterize_axes(raw[ch], dt)
        true = raw[f"true_{ch}"]  # [white, bias_instab(B), tau, rrw]
        results[ch] = fit
        print(f"[{ch}]")
        print(_fmt_row(f"{ch}_white", true[0], fit.white))
        print(_fmt_row(f"{ch}_bias_instab(B)", true[1], fit.bias_instability))
        print(_fmt_row(f"{ch}_bias_tau", true[2], fit.bias_tau))
        rrw_note = "  (below bias floor — not separately identifiable)"
        print(f"  {ch + '_rrw':16s} true {true[3]:11.3e}   rec {fit.rrw:11.3e}{rrw_note}")
        print()

    accel, gyro = results["accel"], results["gyro"]
    # Write the GM steady-state std (sigma_GM) into the *_bias_instability field, since
    # that is what the C++ Imu interprets as the GM steady-state standard deviation.
    config = {
        "_comment": (
            "IMU + seeker noise parameters consumed by the C++ sensor models. GENERATED by "
            "sensors/fit_noise_params.py from Allan-variance characterization of a 4 h static "
            "record (sensors/generate_imu_data.py). *_bias_instability = recovered Gauss-Markov "
            "steady-state std (sigma_GM); the Allan hump-peak bias instability B ~= 0.617*sigma_GM. "
            "The loop-closure test (postproc) confirms the in-sim sensor reproduces these. Units: "
            "accel m/s^2 & VRW (m/s)/sqrt(s); gyro rad/s & ARW rad/sqrt(s); tau s; scale_factor frac."
        ),
        "imu": {
            "accel_white": round(accel.white, 12),
            "accel_bias_instability": round(accel.sigma_gm, 12),
            "accel_bias_tau": round(accel.bias_tau, 4),
            "accel_rrw": round(accel.rrw, 14),
            "accel_scale_factor": ACCEL_SCALE_FACTOR,
            "gyro_white": round(gyro.white, 12),
            "gyro_bias_instability": round(gyro.sigma_gm, 12),
            "gyro_bias_tau": round(gyro.bias_tau, 4),
            "gyro_rrw": round(gyro.rrw, 14),
            "gyro_scale_factor": GYRO_SCALE_FACTOR,
        },
        "seeker": dict(SEEKER_BLOCK),
    }

    CONFIG_PATH.write_text(json.dumps(config, indent=2) + "\n")
    print(f"wrote {CONFIG_PATH.relative_to(REPO_ROOT)}")
    return config


def main() -> None:
    recover_and_write()


if __name__ == "__main__":
    main()
